version: '2.2'

services:
    wordpress_db:
        image: mysql:latest
        command: '--authentication_policy=mysql_native_password'
        volumes:
            - '${PWD}/data:/var/lib/mysql'
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=pass
            - MYSQL_DATABASE=wordpressdb
            - MYSQL_USER=wordpress
            - MYSQL_PASSWORD=wordpress
        expose:
            - 3306
            - 33060
        networks:
            - my-network
    wordpress_site:
        image: wordpress:latest
        volumes:
            - '${PWD}/wp-data:/var/www/html'
        ports:
            - '80:80'
        restart: always
        environment:
            - WORDPRESS_DB_HOST=wordpress_db
            - WORDPRESS_DB_USER=wordpress
            - WORDPRESS_DB_PASSWORD=wordpress
            - WORDPRESS_DB_NAME=wordpressdb
        networks:
            - my-network
volumes:
    db_data:
    wp_data:
networks:
    my-network: