resource_group_name     = "ContactBookRG"
resource_group_location = "West Europe"
app_service_plan_name   = "contact-book-plan"
app_service_name        = "contact-book"
repo_URL                = "https://github.com/nakov/ContactBook"
repo_Branch             = "master"