version: '3.8'

services:
    sqlserver:
        container_name: sqlserver
        image: mcr.microsoft.com/mssql/server
        ports:
            - "1433:1433"
        restart: on-failure
        environment:
            - ACCEPT_EULA=Y"
            - MSSQL_SA_PASSWORD=yourStrongPassword12#
        volumes:
            - sqldata:/var/opt/mssql/server
        networks:
            - my-network
    web_app:
        container_name: web_app
        build:
            dockerfile: ./Dockerfile
        depends_on:
            - sqlserver
        command: ["dotnet", "ef", "database update"]
        ports:
            - '80:80'
        restart: on-failure
        networks:
            - my-network
volumes:
    sqldata:
networks:
    my-network: